apiVersion: batch/v1
kind: Job
metadata:
  labels:
    {{- include "influxdb.labels" . | nindent 4 }}
  name: {{ template "influxdb.fullname" . }}-fix-dbrp
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation"
spec:
  activeDeadlineSeconds: 90
  template:
    metadata:
      labels:
        {{- include "influxdb.labels" . | nindent 8 }}
      annotations:
        io.cribl.scope/disable: 'true'
    spec:
      containers:
      - name: {{ template "influxdb.fullname" . }}-fix-dbrp
        image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
        env:
          - name: INFLUXDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "influxdb.fullname" . }}-auth
                key: admin-password
          - name: INFLUXDB_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ template "influxdb.fullname" . }}-auth
                key: admin-token
        command:
          - bash
        args:
          - -cx
          - |
            influx v1 dbrp create \
            --bucket-id $(influx bucket ls \
              -t ${INFLUXDB_TOKEN} \
              --host http://{{ template "influxdb.fullname" . }}:{{ .Values.service.port }} \
              --org {{ .Values.adminUser.organization }} \
              --name {{ .Values.adminUser.bucket }} \
              --json | \
                grep -oP "id\"\s*:\s*\"\K[^\"]+") \
            --db {{ .Values.adminUser.bucket }} \
            --default \
            --org {{ .Values.adminUser.organization }} \
            --rp forever \
            --host http://{{ template "influxdb.fullname" . }}:{{ .Values.service.port }} \
            -t ${INFLUXDB_TOKEN} || sleep 180
          # - echo foo
          # - -cx
          # - |
          #   apt-get update && apt-get install -y curl jq && \
          #   export BUCKET_ID=$(curl -s -H "Authorization: Token ${INFLUXDB_TOKEN}" -H "Content-Type: application/json" http://{{ template "influxdb.fullname" . }}:{{ .Values.service.port }}/api/v2/buckets?name=cribl | jq -r .buckets[0].id) && \
          #   export ORG_ID=$(curl -s -H "Authorization: Token ${INFLUXDB_TOKEN}" -H "Content-Type: application/json" http://{{ template "influxdb.fullname" . }}:{{ .Values.service.port }}/api/v2/orgs?org=cribl | jq -r .orgs[0].id) && \
          #   curl -X POST -H "Authorization: Token ${INFLUXDB_TOKEN}" -H "Content-Type: application/json" http://{{ template "influxdb.fullname" . }}:{{ .Values.service.port }}/api/v2/dbrps -d "{\"bucket_id\": \"${BUCKET_ID}\",\"database\": \"cribl\",\"default\": true,\"organization\": \"cribl\",\"organization_id\": \"${ORG_ID}\",\"retention_policy\": \"forever\" }"
      restartPolicy: OnFailure
