#!/bin/bash

host=$1
if [ -n "$1" ]; then
  host=$1
else
  host=localhost
fi

if [ -d $CRIBL_HOME/groups ]; then
  CRIBL_GROUPS=$CRIBL_HOME/groups
elif [ -d $CRIBL_VOLUME_DIR/groups ]; then
  CRIBL_GROUPS=$CRIBL_VOLUME_DIR/groups
fi

if [ -n "$CRIBL_GROUPS" ]; then
  # call the cli-auth expect script to log into the cli
  token=$(curl -X POST "http://$host:9000/api/v1/auth/login" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"username\": \"admin\",\"password\":\"cribldemo\"}" | jq -r '.token')

  commit=$(curl -v -X POST "http://$host:9000/api/v1/version/commit" -H  "accept: application/json" -H  "Authorization: Bearer $token" | jq -r '.items[0].commit')
  if [ -z "$commit" ]; then
    echo "No Commit Found, exiting"
    exit 255
  fi

  for grp in $(cd $CRIBL_GROUPS;  ls -1 ); do
    patchdata="{\"version\": \"$commit\", \"id\": \"$grp\"}"
    # Run commit and deploy separately for each worker group (commit-deploy will fail if
    # there is nothing to commit, but we want to push a deploy either way.
    echo $patchdata > /tmp/patch$$
    echo "pdata: $patchdata"
    curl -v -X PATCH -d@/tmp/patch$$ "http://$host:9000/api/v1/master/groups/$grp/deploy" -H  "accept: application/json" -H  "Authorization: Bearer $token" -H "Content-Type: application/json"
    rm /tmp/patch$$
  done

fi
