#!/usr/bin/expect -f

set timeout -1

spawn /opt/cribl/bin/cribl auth login

expect "Enter Cribl LogStream URL (http://localhost:9000):"

send -- "\r"

expect "Enter username:"

send -- "admin\r"

expect "Enter password:"

send -- "cribldemo\r"

expect "Successful login\r"

expect  eof
