---
apiVersion: batch/v1
kind: Job
metadata:
  name: cribl-sa
  labels:
    app.kubernetes.io/name: cribl-sa
spec:
  activeDeadlineSeconds: 660
  template:
    metadata:
      annotations:
        io.cribl.scope/disable: 'true'
      labels:
        app.kubernetes.io/name: cribl-sa
    spec:
      containers:
        - env:
            # - name: CRIBL_AFTER_START_CMD_1
            #   value: sleep 660 && /bin/kill -TERM 1
            - name: CRIBL_HOME
              value: /opt/cribl
          image: cribl-sa
          name: cribl-sa
          ports:
            - containerPort: 9000
            - containerPort: 5140
          resources: 
            limits:
              cpu: 2000m
              memory: 4096Mi
            requests:
              cpu: 750m
              memory: 1024Mi

      restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: cribl-sa
spec:
  selector:
    job-name: cribl-sa
  ports:
  - name: ui 
    port: 9005
    targetPort: 9000
  - name: syslog
    port: 5140
    targetPort: 5140
